COL_TOPIC = "topic"
COL_SENTENCE = "sentence"
COL_SET = "set"
COL_IS_ARGUMENT = "is_argument"
COL_IS_ARGUMENT_PROB = "is_argument_prob"
COL_IS_STRONG = "is_strong"
COL_IS_STRONG_PROB = "is_strong_prob"
COL_STANCE = "stance"
COL_STANCE_CONF = "stance_conf"

STANCE_PRO_LABEL = "For"
STANCE_CON_LABEL = "Against"
STANCE_NO_ARG_LABEL = "None"

SET_TRAIN = "train"
SET_DEV = "dev"
SET_TEST = "test"
